"""adiciona tipo de foto de perfil

Revision ID: 1333aeb2c0db
Revises: 5ae5187047e0
Create Date: 2026-09-18 21:19:20.157113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1333aeb2c0db'
down_revision = '5ae5187047e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil_tipo', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil_tipo')

    # ### end Alembic commands ###
