"""calendario

Revision ID: 3c19e9a06784
Revises: 4bb05ccbefe3
Create Date: 2026-09-18 12:45:10.699736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c19e9a06784'
down_revision = '4bb05ccbefe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento_calendario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dia_resevado', sa.Date(), nullable=False),
    sa.Column('hora_resevada', sa.Time(), nullable=False),
    sa.Column('tipo_evento', sa.Enum('Consulta médica', 'Exame', 'Vacina', 'Registro de glicemia', 'Tomar medicação', name='tipoevento'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='fk_usuario_evento'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evento_calendario', schema=None) as batch_op:
        batch_op.create_index('fk_usuario_id_idx', ['id_usuario'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evento_calendario', schema=None) as batch_op:
        batch_op.drop_index('fk_usuario_id_idx')

    op.drop_table('evento_calendario')
    # ### end Alembic commands ###
