"""criação das tabelas

Revision ID: 4bb05ccbefe3
Revises: 
Create Date: 2026-09-14 08:54:53.860337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bb05ccbefe3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('remember_me', mysql.TINYINT(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('passw_hash', sa.String(length=256), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cuidador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_cuidador', sa.Enum('familiar', 'profissional', name='cuidadortipocuidador'), nullable=True),
    sa.Column('conselho_profissional', sa.String(length=10), nullable=True),
    sa.Column('registro_profissional', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='fk_usuario_cuidador'),
    sa.PrimaryKeyConstraint('id', 'id_usuario')
    )
    with op.batch_alter_table('cuidador', schema=None) as batch_op:
        batch_op.create_index('fk_usuario_cuidador_idx', ['id_usuario'], unique=False)

    op.create_table('paciente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=True),
    sa.Column('genero', sa.CHAR(length=1), nullable=True),
    sa.Column('tipo_diabete', sa.Enum('tipo1', 'tipo2', 'gestacional', name='pacientetipodiabete'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='fk_usuario_paciente'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index('fk_usuario_paciente_idx', ['id_usuario'], unique=False)

    op.create_table('registro_glicemico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('medida', sa.DECIMAL(), nullable=False),
    sa.Column('data_registro', sa.Date(), nullable=False),
    sa.Column('hora_registro', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('Jejum', 'Pré-refeição', 'Pós-refeição', 'Sintomático', 'Atividade física', 'Antes de dormir', 'Madrugada', 'Outro', name='estadopessoal'), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='fk_usuario_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_glicemico', schema=None) as batch_op:
        batch_op.create_index('fk_usuario_id_idx', ['id_usuario'], unique=False)

    op.create_table('responsavel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('responsabilidade', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], name='fk_usuario_responsavel'),
    sa.PrimaryKeyConstraint('id', 'id_usuario')
    )
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.create_index('fk_usuario_responsavel_idx', ['id_usuario'], unique=False)

    op.create_table('vinculocuidador_paciente',
    sa.Column('id_cuidador', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('criado_por_cuidador', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('data_associacao', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'Pendente'"), nullable=True),
    sa.ForeignKeyConstraint(['id_cuidador'], ['cuidador.id'], name='fk_cuidador_vinculo'),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], name='fk_cuidador_paciente'),
    sa.PrimaryKeyConstraint('id_cuidador', 'id_paciente')
    )
    with op.batch_alter_table('vinculocuidador_paciente', schema=None) as batch_op:
        batch_op.create_index('fk_cuidador_paciente_idx', ['id_paciente'], unique=False)

    op.create_table('vinculoresponsavel_paciente',
    sa.Column('id_responsavel', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('relacao', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('ativo', 'desativado', 'pendente', name='vinculoresponsavelpacientestatus'), nullable=True),
    sa.Column('criado_por_responsavel', mysql.TINYINT(), server_default=sa.text("'0'"), nullable=True),
    sa.Column('data_associacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id'], name='fk_paciente_responsavel'),
    sa.ForeignKeyConstraint(['id_responsavel'], ['responsavel.id'], name='fk_responsavel_vinculo'),
    sa.PrimaryKeyConstraint('id_responsavel', 'id_paciente')
    )
    with op.batch_alter_table('vinculoresponsavel_paciente', schema=None) as batch_op:
        batch_op.create_index('fk_paciente_responsavel_idx', ['id_paciente'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vinculoresponsavel_paciente', schema=None) as batch_op:
        batch_op.drop_index('fk_paciente_responsavel_idx')

    op.drop_table('vinculoresponsavel_paciente')
    with op.batch_alter_table('vinculocuidador_paciente', schema=None) as batch_op:
        batch_op.drop_index('fk_cuidador_paciente_idx')

    op.drop_table('vinculocuidador_paciente')
    with op.batch_alter_table('responsavel', schema=None) as batch_op:
        batch_op.drop_index('fk_usuario_responsavel_idx')

    op.drop_table('responsavel')
    with op.batch_alter_table('registro_glicemico', schema=None) as batch_op:
        batch_op.drop_index('fk_usuario_id_idx')

    op.drop_table('registro_glicemico')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index('fk_usuario_paciente_idx')

    op.drop_table('paciente')
    with op.batch_alter_table('cuidador', schema=None) as batch_op:
        batch_op.drop_index('fk_usuario_cuidador_idx')

    op.drop_table('cuidador')
    op.drop_table('usuario')
    # ### end Alembic commands ###
