"""af

Revision ID: 5ae5187047e0
Revises: 870536dd0a49
Create Date: 2026-09-18 19:49:29.961268

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ae5187047e0'
down_revision = '870536dd0a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=5, scale=1),
               existing_nullable=True)

    with op.batch_alter_table('registro_glicemico', schema=None) as batch_op:
        batch_op.alter_column('medida',
               existing_type=mysql.DECIMAL(precision=5, scale=2),
               type_=sa.DECIMAL(precision=5, scale=1),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_glicemico', schema=None) as batch_op:
        batch_op.alter_column('medida',
               existing_type=sa.DECIMAL(precision=5, scale=1),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=sa.DECIMAL(precision=5, scale=1),
               type_=mysql.DECIMAL(precision=5, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
