"""mudanças

Revision ID: 870536dd0a49
Revises: d8d67b309773
Create Date: 2026-09-18 19:26:00.309506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '870536dd0a49'
down_revision = 'd8d67b309773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.DECIMAL(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('registro_glicemico', schema=None) as batch_op:
        batch_op.alter_column('medida',
               existing_type=mysql.DECIMAL(precision=10, scale=0),
               type_=sa.DECIMAL(precision=5, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('peso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', mysql.DECIMAL(precision=10, scale=0), nullable=True))

    with op.batch_alter_table('registro_glicemico', schema=None) as batch_op:
        batch_op.alter_column('medida',
               existing_type=sa.DECIMAL(precision=5, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=0),
               existing_nullable=False)

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
